import { CategoryVariant, ItemDataType, SizeTypeVariant } from "./types/types";

export const jsonData: ItemDataType[] = [
  {
    id: 1,
    src: "https://magnitcosmetic.ru/upload/iblock/3e6/3e62e768a29b9de5fa485730c80c087f.jpeg",
    title: "Крем для рук Лимонно-глицериновый",
    sizeType: SizeTypeVariant.ml,
    size: 50,
    barcode: 30014914,
    producer: "Юниливер",
    brand: "Невская косметика",
    description: "Этот легкий крем хорошо увлажняет кожу и сохраняет ее естественную влагу. Он содержит натуральный глицерин и богатый витамином С экстракт лимона, который обеспечивает витаминное питание кожи, оказывает антисептическое действие, а также обеспечивает легкое отбеливание кожи рук и способствует укреплению ногтевой пластины. Крем обладает приятным запахом, легко распределяется по коже и быстро впитывается, не оставляя чувства липкости.",
    price: 105,
    category: [CategoryVariant.hand, CategoryVariant.hygiene, CategoryVariant.sunscreen]
  },
  {
    id: 2,
    src: "https://magnitcosmetic.ru/upload/iblock/fa4/fa4b6a57a38baaf51df43a22898e09cc.jpeg",
    title: "Скраб для тела Цветы граната",
    sizeType: SizeTypeVariant.ml,
    size: 290,
    barcode: 11278135843,
    producer: "Юниливер",
    brand: "Camay",
    description: "Как и всегда продукцию нашей компании отличают высокое качество используемых компонентов, оригинальность и удобство упаковки, привлекательная цена, высокая узнаваемость потребителем, что делает данный продукт несомненным хитом продаж. Теперь каждый пакетик снабжен вырубкой, что сделало продукт более удобным в размещении на различном дополнительном оборудовании.",
    price: 322,
    category: [CategoryVariant.body, CategoryVariant.sunscreen]
  },
  {
    id: 3,
    src: "https://magnitcosmetic.ru/upload/iblock/4c2/4c2b888cfbd081a7bfbb30fadb1c43bd.jpeg",
    title: "Глина белая косметическая отбеливающая ",
    sizeType: SizeTypeVariant.gr,
    size: '60',
    barcode: 135961283,
    producer: "Юниливер",
    brand: "Fito",
    description: "ксклюзивная серия продуктов по уходу за кожей лица и тела на основе глин – это уникальные средства для устранения широкого спектра косметических проблем.",
    price: 30,
    category: ['уход за телом']
  },
  {
    id: 4,
    src: "https://udvolga.ru/image/cache/catalog/Olea-228x228.jpg",
    title: "Крем для ног восстанавливающий",
    sizeType: SizeTypeVariant.ml,
    size: 200,
    barcode: 5312130811,
    producer: "SCHWARZKOPF",
    brand: "OLEA",
    description: "Против загрязнений окружающей среды.Мочевина 10% в составе обладает антисептическими и дезодирующими свойствами, хорошо увлажняет, смягчает сухую огрубевшую кожу и предотвращает потерю влаги.",
    price: 83,
    category: [CategoryVariant.body, CategoryVariant.legs]
  },
  {
    id: 5,
    src: "https://magnitcosmetic.ru/upload/iblock/fac/fac9f3d901d735a1bfbfb255939328a9.jpeg",
    title: "«Основной уход, Экстракт Винограда» для нормальной и смешанной кожи",
    sizeType: SizeTypeVariant.ml,
    size: 200,
    barcode: 40000958,
    producer: "LOREAL",
    brand: "Garnier",
    description: "Очищающие средства гаммы Основной Уход на 96% состоят из ингредиентов натурального происхождения. Молочко для снятия макияжа обогащено Экстрактом Винограда, известного как природный источник свежести. ",
    price: 383,
    category: [CategoryVariant.face, CategoryVariant.shave]
  },
  {
    id: 6,
    src: "https://magnitcosmetic.ru/upload/iblock/e44/e4487cfa37b26b12ff832bcc34240cfd.jpeg",
    title: "Мусс для умывания матирующий",
    sizeType: SizeTypeVariant.ml,
    size: 160,
    barcode: 8714100,
    producer: "LOREAL",
    brand: "Dove",
    description: "Матирующий мусс Dove предназначен для очищения кожи лица. Подходит для комбинированной и склонной к жирности кожи с расширенными порами. ",
    price: 402,
    category: [CategoryVariant.face, CategoryVariant.sunscreen]
  },
  {
    id: 7,
    src: "https://magnit.ru/upload/iblock/2bd/2bd7c39b19f5c09b3e1b76a4441907c6.png",
    title: "Салфетки влажные для снятия макияжа",
    sizeType: SizeTypeVariant.gr,
    size: 20,
    barcode: 871413200,
    producer: "LOREAL",
    brand: "Я САМАЯ ",
    description: "Подходит для комбинированной и склонной к жирности кожи с расширенными порами. ",
    price: 402,
    category: [CategoryVariant.face, CategoryVariant.body, CategoryVariant.hand, CategoryVariant.legs, CategoryVariant.paper, CategoryVariant.hygiene]
  },
  {
    id: 8,
    src: "https://magnitcosmetic.ru/upload/iblock/43e/43ec0389412f08389c1ae0e1ab919ef1.jpeg",
    title: "Зубная паста «клубника/мята», 6-9 лет, с фторидом",
    sizeType: SizeTypeVariant.ml,
    size: 60,
    barcode: 69203548256,
    producer: "КОЛГЕЙТ-ПАЛМОЛИВ АО",
    brand: "Colgate",
    description: "Новая детская паста от любимого бренда Colgate 6-9, предназначена для ухода за появляющимися постоянными зубами детишек.-Не содержит SLES, парабенов, глютена, сахара",
    price: 249,
    category: [CategoryVariant.mouth, CategoryVariant.hygiene]
  },
  {
    id: 9,
    src: "https://magnitcosmetic.ru/upload/iblock/af2/af22892159f761f316affae1c4db98f9.jpeg",
    title: "Зубная щетка средней жесткости",
    sizeType: SizeTypeVariant.gr,
    size: 20,
    barcode: 68930509,
    producer: "КОЛГЕЙТ-ПАЛМОЛИВ АО",
    brand: "Biomed",
    description: "Полипропилен, термопластичный эластомер; щетина – полибутилентерефталат.",
    price: 159,
    category: [CategoryVariant.mouth]
  },
  {
    id: 10,
    src: "https://magnitcosmetic.ru/upload/iblock/899/899e5052933ebc58365a2aadee4c7157.jpeg",
    title: "Зубной порошок отбеливание",
    sizeType: SizeTypeVariant.gr,
    size: 50,
    barcode: 60671148,
    producer: "SCHWARZKOPF",
    brand: "Аванта",
    description: "Зубной порошок «Семейный» прекрасно очищает зубы от налета, при этом возвращая естественную белизну зубов. Благодаря натуральным компонентам в составе, порошок отлично освежает дыхание и поддерживает здоровое состояние десен и слизистой полости рта.",
    price: 37,
    category: [CategoryVariant.mouth]
  },
  {
    id: 11,
    src: "https://magnitcosmetic.ru/upload/iblock/d6c/d6ccfd1319c80d999b57b981aeff9269.jpeg",
    title: "Антиперспирант-спрей",
    sizeType: SizeTypeVariant.ml,
    size: 150,
    barcode: 7008964,
    producer: "Юниливер",
    brand: "Axe",
    description: "Isobutane, Alcohol Denat., Parfum, Propane, Butane, Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl Benzoate, Benzyl Salicylate, Butylphenyl Methylpropional, Citral, Citronellol, Geraniol, Limonene, Linalool.",
    price: 237,
    category: [CategoryVariant.body, CategoryVariant.hygiene, CategoryVariant.presentBox]
  },
  {
    id: 12,
    src: "https://magnitcosmetic.ru/upload/iblock/b12/b1201ce404376ce839307917d096048c.jpeg",
    title: "Набор: Шампунь + Кондиционер для ухода за окрашенными волосами «Масло орхидеи»",
    sizeType: SizeTypeVariant.ml,
    size: 385,
    barcode: 4661642,
    producer: "SCHWARZKOPF",
    brand: "Ogx",
    description: "Шампунь OGX® для ухода за окрашенными волосами «Масло орхидеи» помогает сохранить цвет окрашенных волос с помощью формулы, содержащей экстракт орхидеи и масло виноградных косточек. C бессульфатов моющей основой бережно очищает волосы, замедляя вымывание. Помогает восстанавливать и укреплять волосы, придавая им мягкость и ослепительный блеск.",
    price: 1290,
    category: [CategoryVariant.hair, CategoryVariant.presentBox]
  },
  {
    id: 13,
    src: "https://magnitcosmetic.ru/upload/iblock/58c/58c1f45daacc09cba8367122258a3f03.jpeg",
    title: "Косметический набор «Тушь для ресниц Black Star 3 в 1 и губная помада тон F23»",
    sizeType: SizeTypeVariant.gr,
    size: 236,
    barcode: 60200623,
    producer: "Stellary",
    brand: "Stellary",
    description: "Подарочный набор Stellary состоит из двух средств: Тушь для ресниц Stellary Black Star насыщенного черного цвета с тройным эффектом: удлинение, изгиб и разделение с удобной формой щеточки в один взмах сделает взгляд дерзким.",
    price: 2280,
    category: [CategoryVariant.face, CategoryVariant.presentBox]
  },
  {
    id: 14,
    src: "https://magnitcosmetic.ru/upload/iblock/d83/d83f5c2cc2808f8bae010088659b6c62.jpeg",
    title: "Набор Peach Skin, кожа как персик «Базовый Уход», увлажнение",
    sizeType: SizeTypeVariant.gr,
    size: 500,
    barcode: 60200623,
    producer: "Stellary",
    brand: "Sammy Beauty",
    description: "В этом наборе есть все необходимое, чтобы выглядеть на максимум и потратить минимум времени на уход: очищающий мицеллярный гель, деликатный скраб и увлажняющий крем.",
    price: 900,
    category: [CategoryVariant.face, CategoryVariant.presentBox, CategoryVariant.hand, CategoryVariant.legs, CategoryVariant.body]
  },
  {
    id: 15,
    src: "https://magnitcosmetic.ru/upload/iblock/ee1/ee1926ba7808d798112751fa578cdf1a.jpeg",
    title: "Полотенце кухонное кухонное велюровое",
    sizeType: SizeTypeVariant.gr,
    size: 10,
    barcode: 201000036,
    producer: "Stellary",
    brand: "ТЕКСТАИЛЗ",
    description: "В этом наборе есть все необходимое, чтобы выглядеть на максимум и потратить минимум времени на уход: очищающий мицеллярный гель, деликатный скраб и увлажняющий крем.",
    price: 100,
    category: [CategoryVariant.face, CategoryVariant.presentBox, CategoryVariant.hand, CategoryVariant.legs, CategoryVariant.body, CategoryVariant.paper]
  },
  {
    id: 16,
    src: "https://magnitcosmetic.ru/upload/iblock/e78/e78b24b40f8e09b283bc522d2822afed.jpeg",
    title: "Тёплый воск для депиляции",
    sizeType: SizeTypeVariant.ml,
    size: 250,
    barcode: 468001239022,
    producer: "BENCKISER",
    brand: "Veet",
    description: "Теплый воск Veet. Профессиональное качество в домашних условиях. Воск основан на натуральных ингредиентах. Он удаляет волосы с первого раза, оставляя кожу гладкой до 4-х недель.",
    price: 900,
    category: [CategoryVariant.shave, CategoryVariant.legs, CategoryVariant.body, CategoryVariant.paper]
  },
  {
    id: 17,
    src: "https://magnitcosmetic.ru/upload/iblock/f7f/f7f9b309df09d36dacbb9731480117b1.jpeg",
    title: "Пена для бритья",
    sizeType: SizeTypeVariant.gr,
    size: 400,
    barcode: 10041200300,
    producer: "BENCKISER",
    brand: "Figaro",
    description: "Пена для бритья торговой марки Figaro uomo. Мужская серия. Пена для бритья Figaro uomo подходит для всех типов кожи, создает защитный слой и облегчает скольжение бритвенного станка.",
    price: 900,
    category: [CategoryVariant.shave, CategoryVariant.legs, CategoryVariant.body, CategoryVariant.paper]
  },
  {
    id: 18,
    src: "https://magnitcosmetic.ru/upload/iblock/7f9/7f9d5166e8a5700a672675bc534760b2.jpeg",
    title: "«Экстремальный Oil-эликсир» для сухих и ослабленных волос",
    sizeType: SizeTypeVariant.ml,
    size: 200,
    barcode: 101500099,
    producer: "BENCKISER",
    brand: "Gliss Kur",
    description: "Бальзам Gliss Kur «Экстремальный Oil-эликсир» интенсивно питает и восстанавливает структуру волос.",
    price: 900,
    category: [CategoryVariant.hair, CategoryVariant.sunscreen]
  },
  {
    id: 19,
    src: "https://magnitcosmetic.ru/upload/iblock/4e5/4e5acf13757d687119279b7f60bf5017.jpeg",
    title: "«Экстремальный Oil-эликсир» для сухих и ослабленных волос",
    sizeType: SizeTypeVariant.ml,
    size: 200,
    barcode: 469049403,
    producer: "LOREAL",
    brand: "Concept",
    description: "Бальзам Gliss Kur «Экстремальный Oil-эликсир» интенсивно питает и восстанавливает структуру волос.",
    price: 290,
    category: [CategoryVariant.hair]
  },
];

export const categoryList = [CategoryVariant.all ,CategoryVariant.body, CategoryVariant.hand, CategoryVariant.legs, CategoryVariant.face, CategoryVariant.hair, CategoryVariant.sunscreen, CategoryVariant.shave, CategoryVariant.presentBox, CategoryVariant.hygiene, CategoryVariant.mouth, CategoryVariant.paper]

export const producersData = ['LOREAL', 'BENCKISER', 'Stellary', 'Юниливер', 'SCHWARZKOPF', 'КОЛГЕЙТ-ПАЛМОЛИВ АО']